# site url
url: http://www.vitruvio.in
baseurl: ''

# Site settings
title: Vitruvio Groups
email: vitruviogroups@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Asif Munavar
  pic: 1
  position: Co-Founder
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

- name: Lovely Jain
  pic: 2
  position: Designer
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

- name: Rishabh Agarwal
  pic: 3
  position: Project Manager
 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url: https://www.facebook.com/vitruviodevelopers
  - title: instagram
    url: https://www.instagram.com/vitruviogroups/
  - title:  
    url: 
  - title: 
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Bengaluru,Karnataka.
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
